### PR TITLE
Fix: Missing certificate signed by unknown authority refs: https://gi…

### PR DESCRIPTION
**Pull request by craph**
#### Summary

Here is the pull request to fix the issue I open about missing code that I already PR in the previous repository.

#### Ticket Link

Fixes https://github.com/mattermost/docker/issues/34

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
lgtm

**Comment by craph** [comment]
Hello @mrckndt, 

Please could you have a look ?

Best regards,

**Comment by craph** [comment]
> @craph Thank you so much!

@metanerd You're welcome

**Comment by craph** [comment]
@metanerd , @cpanato , @mrckndt I did a new PR #52 for this issue because I made a mistake in #49.

You already accepted and merger those changes but in #49 the changes was revert 😢 I'm very sorry for the mistake.

Thanks to all of you for applying #52 again to fix my mistake.

Best regards,

**Pull request merged**
