### PR TITLE
Simplify README

### PR DESCRIPTION
**Pull request by azigler**
#### Summary
Updated README to point to new Docker documentation as part of [mattermost/docsPR#5539](https://github.com/mattermost/docs/pull/5539). Once that is merged, this PR will eliminate redundancy.

CC: @cwarnermm @BenLloydPearson @nab-77

### CODE REVIEW

**Comment by BenLloydPearson** [comment]
@azigler Would you mind either resubmitting this via a branch on this repo, or give us the ability to modify your fork? I want to propose some changes, but can't.

**Comment by azigler** [comment]
@BenLloydPearson Just added you as a contributor. I can't make a fork directly on the repo because I don't have write access.

**Comment by BenLloydPearson** [comment]
@azigler I made some modifications to beef up the readme a bit; nothing huge. For context, I try to follow the [standard readme format](https://github.com/RichardLitt/standard-readme) as much as I can because its a format that has served me very well for a while.

**Comment by BenLloydPearson** [comment]
@svelle Would you be willing to help us merge this? There is one link that doesn't work until we merge [this PR](https://github.com/mattermost/docs/pull/5517) but everything else should be good to go.

**Comment by azigler** [comment]
> @azigler I made some modifications to beef up the readme a bit; nothing huge. For context, I try to follow the [standard readme format](https://github.com/RichardLitt/standard-readme) as much as I can because its a format that has served me very well for a while.

@BenLloydPearson Very nice, thanks for this improvement! I'm familiar with `standard-readme` and think it's an A+ model, so I'll keep that in mind for future README adjustments.

**Pull request merged**
