### PR TITLE
Fix bad location for GITLAB_PKI_CHAIN_PATH option

### PR DESCRIPTION
**Pull request by craph**
#### Summary

Here is the pull request to fix the issue I open about missing code that I already PR in the previous repository.

This PR is to fix a wrong location commited in https://github.com/mattermost/docker/pull/52

I'm using it in Production and the right place is in `docker-compose.yml` not in `docker-compose.nginx.yml`

@hanzei Please could you ask for a review ?

@metanerd, @cpanato, @mrckndt Please could you have a look into this one ?

Thank you very much and sorry for the mistake

#### Ticket Link

Fixes https://github.com/mattermost/docker/issues/34
_Originally posted by @craph in https://github.com/mattermost/mattermost-docker/pull/529#issuecomment-912340798_

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by craph** [comment]
Hello @mrckndt , @hanzei , @cpanato 
Any news about the review of this PR ? I'm using it in production and it's working😃
Thank you very much 😃 
Best regards,

**Comment by craph** [comment]
Hello @mrckndt please could you have a look and approve the fix for the wrong location on my previous PR as I explained in the description ? 😃 

Thank you very much. 🙏

**Comment by craph** [comment]
Hi @hanzei ,

Do you have any news about this PR ?

Thank you very much 🙏

**Comment by craph** [comment]
Hello, is it possible to have any news about my PR ? I opened it 1 months ago 😢 
It's just a move of code in the right docker-compose file because I did it wrong in the previous PR.
Thank you very much.

**Comment by hanzei** [comment]
Got approval from  @mrckndt offline

**Pull request merged**
